version = "0.4.5"
author = "Contract ABI Authors"
description = "ABI Encoding for Ethereum contracts"
license = "MIT"

requires "stint"
requires "stew"
requires "nimcrypto >= 0.5.4 & < 0.6.0"
requires "questionable >= 0.10.0 & < 0.11.0"
requires "upraises >= 0.1.0 & < 0.2.0"
