name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim: [1.6.14, 2.0.14, stable]
    steps:
    - uses: actions/checkout@v2
    - uses: iffy/install-nim@v3
      with:
        version: ${{ matrix.nim }}
    - name: Build
      run: nimble install -y
    - name: Test
      run: nimble test -y
